// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARSHHgfYh5mL-9PM7Qd4fdLBkeWcMWfIM',
    appId: '1:468631315837:web:34e89e06c874b9e58c9814',
    messagingSenderId: '468631315837',
    projectId: 'flutter-mvvm-gamer-e27d0',
    authDomain: 'flutter-mvvm-gamer-e27d0.firebaseapp.com',
    storageBucket: 'flutter-mvvm-gamer-e27d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmU9lonYuc1IyU6eDiRjrJ7_SMS4N4Lo',
    appId: '1:468631315837:android:95771b61b98310538c9814',
    messagingSenderId: '468631315837',
    projectId: 'flutter-mvvm-gamer-e27d0',
    storageBucket: 'flutter-mvvm-gamer-e27d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGRyvTWs8LCApkUxWm7F09a7EpzFs-3xo',
    appId: '1:468631315837:ios:980918d25b03b66e8c9814',
    messagingSenderId: '468631315837',
    projectId: 'flutter-mvvm-gamer-e27d0',
    storageBucket: 'flutter-mvvm-gamer-e27d0.firebasestorage.app',
    iosBundleId: 'com.example.gamerMvvmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGRyvTWs8LCApkUxWm7F09a7EpzFs-3xo',
    appId: '1:468631315837:ios:980918d25b03b66e8c9814',
    messagingSenderId: '468631315837',
    projectId: 'flutter-mvvm-gamer-e27d0',
    storageBucket: 'flutter-mvvm-gamer-e27d0.firebasestorage.app',
    iosBundleId: 'com.example.gamerMvvmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARSHHgfYh5mL-9PM7Qd4fdLBkeWcMWfIM',
    appId: '1:468631315837:web:e8c5cb537881f6268c9814',
    messagingSenderId: '468631315837',
    projectId: 'flutter-mvvm-gamer-e27d0',
    authDomain: 'flutter-mvvm-gamer-e27d0.firebaseapp.com',
    storageBucket: 'flutter-mvvm-gamer-e27d0.firebasestorage.app',
  );

}